# Development docker-compose for local development with hot reloading

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: airline-voucher-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_dev_data:/app/data
    environment:
      - GIN_MODE=debug
      - DB_PATH=/app/data/vouchers.db
    working_dir: /app
    command: go run main.go
    restart: unless-stopped
    networks:
      - airline-network-dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: airline-voucher-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend-dev
    restart: unless-stopped
    networks:
      - airline-network-dev

volumes:
  backend_dev_data:
    driver: local

networks:
  airline-network-dev:
    driver: bridge
