services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: airline-voucher-backend
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/root/data
    environment:
      - GIN_MODE=release
      - DB_PATH=/root/data/vouchers.db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - airline-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: airline-voucher-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - airline-network

volumes:
  backend_data:
    driver: local

networks:
  airline-network:
    driver: bridge
